#!/usr/bin/env bash
# Run an automated SuperFX (GSU) unit test.
# Usage: ./run_test.sh [test_directory]

set -euo pipefail

TEST_DIR="${1:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Gate 1: Pre-flight Verification
if [ ! -d "$TEST_DIR" ]; then
    echo "Error: Test directory not found: $TEST_DIR" >&2
    exit 1
fi

DIR_NAME="$(basename "$TEST_DIR")"
if [ "$DIR_NAME" = "test_template" ]; then
    echo "Error: tests/test_template is a scaffold template, not an executable unit test suite." >&2
    echo "Use create-gsu-test to create a new test from this template." >&2
    exit 1
fi

for req_file in "Makefile" "Test.s" "Test.sgs" "test.lua"; do
    if [ ! -f "$TEST_DIR/$req_file" ]; then
        echo "Error: Required test file '$req_file' missing in $TEST_DIR." >&2
        exit 1
    fi
done

# Gate 2: Clean Compilation
echo "=== Step 1: Compiling test in $TEST_DIR (make clean all) ==="
if ! make -C "$TEST_DIR" clean all; then
    echo "Error: Build failed in $TEST_DIR. Aborting test execution." >&2
    exit 1
fi

if [ ! -f "$TEST_DIR/Test.cpu.sym" ]; then
    echo "Error: Symbol file '$TEST_DIR/Test.cpu.sym' was not generated by build." >&2
    exit 1
fi

if [ ! -f "$TEST_DIR/Test.sfc" ]; then
    echo "Error: ROM binary '$TEST_DIR/Test.sfc' was not generated by build." >&2
    exit 1
fi

# Gate 3 & 4: Symbol Synchronization & Emulation Termination Check
echo "=== Step 2: Synchronizing symbols and validating test.lua ==="
if ! python3 "$SCRIPT_DIR/sync_test_labels.py" "$TEST_DIR/Test.cpu.sym" "$TEST_DIR/test.lua"; then
    echo "Error: Symbol synchronization or pre-execution validation failed. Aborting test execution." >&2
    exit 1
fi

# Gate 5: Mesen Availability & Execution
MESEN_BIN="$(command -v Mesen || command -v mesen || true)"
if [ -z "$MESEN_BIN" ]; then
    # Fallback to local user path if on macOS
    if [ -x "/Users/summerspittman/Programs/Mesen" ]; then
        MESEN_BIN="/Users/summerspittman/Programs/Mesen"
    fi
fi

if [ -z "$MESEN_BIN" ] || [ ! -x "$MESEN_BIN" ]; then
    echo "Error: Mesen executable not found on system PATH." >&2
    exit 1
fi

echo "=== Step 3: Executing Mesen test runner ==="
set +e
(
    cd "$TEST_DIR"
    "$MESEN_BIN" --testrunner test.lua Test.sfc
)
EXIT_CODE=$?
set -e

echo ""
if [ $EXIT_CODE -eq 0 ]; then
    echo "=== TEST PASSED ==="
else
    echo "=== TEST FAILED (Exit Code: $EXIT_CODE) ==="
fi

exit $EXIT_CODE

